### PR TITLE
Adding RN Jesus

### PR DESCRIPTION
**Pull request by cw0102**
Implement RandomNumbers.scala

### CODE REVIEW

**Comment by mandyMooreFan** [comment]
In the future please don't commit to master even on your own person fork.  We are not animals.

**Comment by cw0102** [comment]
😩

**Comment by mandyMooreFan** [comment]
Looks good I will keep the #6 open till we add tests for this.

https://softwareengineering.stackexchange.com/questions/147134/how-should-i-test-randomness

**Comment by mandyMooreFan** [comment]
Closes #6 

Great pull request @cw0102.

**Pull request merged**
